Repository Rolling-Paper-Project/Rolling-Page, pull requests merged in 2022-08, with the labels that each got.

#1 :tada: set : 초기 세팅 완료
  .eslintrc.js
  .gitignore
  .prettierrc
  README.md
  dist/app/app.js
  dist/app/app.js.map
  dist/components/Post.js
  dist/components/Post.js.map
  dist/elements/Input.js
  dist/elements/Input.js.map
  dist/index.js
  dist/index.js.map
  dist/pages/Board.js
  dist/pages/Board.js.map
  package-lock.json
  package.json
  public/index.html
  src/app/app.tsx
  src/assets/readme.md
  src/components/Post.tsx
  src/elements/Input.tsx
  src/index.tsx
  src/pages/Board.tsx
  tsconfig.json
Labels: set

#2 :pencil2: .eslintrc.js 오타 수정
  .eslintrc.js
Labels: etc

#3 :bento: set : assets폴더 및 이미지 파일 추가
  src/assets/emoji-angry.png
  src/assets/emoji-angry.svg
  src/assets/emoji-cute.png
  src/assets/emoji-cute.svg
  src/assets/emoji-happy.png
  src/assets/emoji-happy.svg
  src/assets/emoji-sad-fun.png
  src/assets/emoji-sad-fun.svg
  src/assets/emoji-sad.png
  src/assets/emoji-sad.svg
  src/assets/emoji-teasing.png
  src/assets/emoji-teasing.svg
  src/assets/icon-close.png
  src/assets/icon-close.svg
  src/assets/icon-copy.png
  src/assets/icon-copy.svg
  src/assets/icon-kakao.png
  src/assets/icon-kakao.svg
  src/assets/readme.md
Labels: set

#6 Feat/element-input 개발 #5
  dist/elements/Input.js
  dist/elements/Input.js.map
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/elements/Input.tsx
  src/index.tsx
Labels: element

#14 :lipstick: feat: Button 엘리먼트 생성
  src/elements/button.tsx
Labels: element, style

#11 💄 feat : Input/Component 개발
  .eslintrc.js
  dist/components/AuthorInput/AuthorInput.js
  dist/components/AuthorInput/AuthorInput.js.map
  dist/components/contentsInput/ContentsInput.js
  dist/components/contentsInput/ContentsInput.js.map
  dist/components/nicknameInput/AuthorInput.js
  dist/components/nicknameInput/AuthorInput.js.map
  dist/components/titleInput/TitleInput.js
  dist/components/titleInput/TitleInput.js.map
  dist/elements/input/Input.js
  dist/elements/input/Input.js.map
  package-lock.json
  package.json
  src/components/authorInput/AuthorInput.tsx
  src/components/contentsInput/ContentsInput.tsx
  src/components/titleInput/TitleInput.tsx
  src/custom.d.ts
  src/elements/Input.tsx
  src/elements/input/Input.tsx
Labels: element, component

#17 :lipstick: Feat: 버튼 element_카카오톡 버튼 추가
  dist/app/app.js
  dist/app/app.js.map
  dist/components/container/Container.js
  dist/components/container/Container.js.map
  dist/elements/button.js
  dist/elements/button.js.map
  src/app/app.tsx
  src/custom.d.ts
  src/elements/button.tsx
Labels: element, style

#19 ✨ feat : post 컴포넌트 개발
  src/components/container/Container.tsx
  src/components/post/Post.tsx
Labels: component

#18 :lipstick: 헤더 컴포넌트 UI 구현, 링크 기능
  src/assets/icon-github.png
  src/assets/icon-github.svg
  src/assets/icon-logo.png
  src/assets/icon-logo.svg
  src/components/Header/Header.tsx
  src/components/Header/headerStyle.tsx
Labels: component, style

#22 ♿ modify : article요소 헤딩태그 추가
  src/components/post/Post.tsx
Labels: component

#23 :lipstick: modify : 수평 스크롤 제거
  src/components/container/Container.tsx
Labels: style

#24 :wrench: add : 정적변수 추가
  dist/constants/index.js
  dist/constants/index.js.map
  src/constants/index.ts
Labels: set

#25 ✨ feat : post 데이터 api연결
  .vscode/settings.json
  package-lock.json
  package.json
  src/components/Post.tsx
  src/components/container/Container.tsx
Labels: set, component, feature

#29 :sparkles: feat : Router 코드 작성
  dist/app/app.js
  dist/app/app.js.map
  src/app/app.tsx
Labels: set

#30 :lipstick: style : 보드 커스텀스크롤 적용
  src/components/container/Container.tsx
Labels: component

#32 :seedling: add : page 파일 및 Main 가코드 추가
  dist/pages/board/Board.js
  dist/pages/board/Board.js.map
  dist/pages/fixedBoard/FixedBoard.js
  dist/pages/fixedBoard/FixedBoard.js.map
  dist/pages/main/Main.js
  dist/pages/main/Main.js.map
  src/pages/Board.tsx
  src/pages/board/Board.tsx
  src/pages/fixedBoard/FixedBoard.tsx
  src/pages/main/Main.tsx
Labels: page

#33 ✨ feat : 포스트 임시데이터 map으로 뿌려주기
  src/components/container/Container.tsx
  src/components/post/Post.tsx
Labels: component, feature

#34 :lipstick: 타이틀 input 컴포넌트에 button element 추가 구현
  src/components/titleInput/TitleInput.tsx
  src/components/titleInput/titleInputStyle.tsx
  src/elements/button.tsx
Labels: component, style

#37 :lipstick: style : 스티커&포스트작성 모달 컴포넌트 UI 구현
  src/components/emojiModal/EmojiModal.tsx
  src/components/emojiModal/emojiModalStyle.ts
Labels: component, style

#39 :lipstick: feat : 삭제모달창 UI 구현
  src/components/deleteModal/DeleteModal.tsx
  src/components/deleteModal/deleteModalStyle.tsx
Labels: component, style

#40 :truck: modify : package.json 충돌 해결
  package.json
Labels: set

#42 ✨ feat : post 랜덤색상 구현
  src/components/container/Container.tsx
  src/constants/index.ts
Labels: component, feature

#46 :truck: Modify : 버튼 import할때의 경로 수정
  src/components/deleteModal/DeleteModal.tsx
  src/components/emojiModal/EmojiModal.tsx
  src/components/titleInput/titleInputStyle.tsx
Labels: etc

#47 :lipstick: modify : 이모지 모달 UI 수정
  src/components/emojiModal/EmojiModal.tsx
  src/components/emojiModal/emojiModalStyle.ts
Labels: element, style

#48 ✨ feat : post api 데이터 불러와서 뿌려주기
  src/components/container/Container.tsx
Labels: feature

#49 :bug: add : Emoji.tsx파일에서 export 추가
  src/elements/emoji/Emoji.tsx
Labels: bug

#50 :hammer: add : 정적변수 추가
  dist/components/Header/Header.js
  dist/components/Header/Header.js.map
  dist/constants/index.js
  dist/constants/index.js.map
  src/components/Header/Header.tsx
  src/components/authorInput/AuthorInput.tsx
  src/constants/index.ts
  tsconfig.json
Labels: etc, style

#52 :sparkles: feat : 타이틀 등록 기능 구현
  src/components/titleInput/TitleInput.tsx
  src/components/titleInput/titleInputStyle.tsx
  src/elements/buttons/button.tsx
  src/elements/input/Input.tsx
Labels: element, component, style, feature

#54 :sparkles: feat: 카카오톡 API 연동 및 버튼 UI 수정
  src/components/shareModal/Share.tsx
  src/components/shareModal/copyUrl.tsx
  src/components/shareModal/kakao.tsx
  src/elements/buttons/button.tsx
  src/elements/buttons/shareBtn.tsx
  src/types/index.d.ts
Labels: component, feature

#55 💄 modify : 포스트 컴포넌트 이미지 적용
  src/app/app.tsx
  src/components/post/Post.tsx
Labels: component, style

#57 :lipstick: feat : 헤더 로고 및 스타일 변경
  src/assets/icon-logo.png
  src/assets/icon-logo.svg
Labels: style

#58 :sparkles: feat : 포스트 삭제 기능 구현
  src/components/deleteModal/DeleteModal.tsx
  src/components/post/Post.tsx
  src/elements/emoji/Emoji.tsx
Labels: feature

#62 :bug: fix: 카카오 공유하기 API 에러 수정
  src/components/shareModal/Share.tsx
  src/components/shareModal/kakao.tsx
Labels: bug, component, feature

#63 :lipstick: feat : 헤더, 타이틀 스타일 수정
  src/components/titleInput/titleInputStyle.tsx
Labels: style

#64 💄 feat : 헤더 스타일 수정
  src/components/Header/headerStyle.tsx
Labels: style

#65 :white_check_mark: feat: 카카오 공유모달 해당 페이지 url로 변경
  src/components/shareModal/Share.tsx
  src/components/shareModal/kakao.tsx
Labels: bug, component

#67 ✨ feat : 완성된 보드일 시 타이틀인풋, 포스트 추가, 삭제버튼 display none
  src/app/app.tsx
  src/components/container/Container.tsx
  src/components/post/Post.tsx
  src/components/titleInput/TitleInput.tsx
  src/components/titleInput/titleInputStyle.tsx
  src/pages/board/Board.tsx
  src/pages/fixedBoard/FixedBoard.tsx
Labels: page, feature

#69 :lipstick: feat : main UI 구현
  src/components/container/Container.tsx
  src/pages/main/Main.tsx
Labels: component, style

#70 :sparkles: feat : 포스트 삭제 및 스타일 수정
  src/components/container/Container.tsx
  src/components/deleteModal/DeleteModal.tsx
  src/components/deleteModal/deleteModalStyle.tsx
  src/components/post/Post.tsx
Labels: style, feature

#73 :lipstick: style : 헤더, 메인 스타일 수정
  src/components/Header/Header.tsx
  src/components/Header/headerStyle.tsx
  src/pages/board/Board.tsx
  src/pages/main/Main.tsx
Labels: component, style

#74 :lipstick: style : 이모지모달 스타일 수정
  src/components/emojiModal/EmojiModal.tsx
  src/components/emojiModal/emojiModalStyle.ts
Labels: style

#75 :sparkles: feat : 삭제 모달 뒷배경 클릭시 모달창 닫기
  src/components/deleteModal/DeleteModal.tsx
  src/components/post/Post.tsx
Labels: feature

#80 ✨ feat : 미리보기 버튼 구현
  src/app/app.tsx
  src/components/container/Container.tsx
  src/components/post/Post.tsx
Labels: component, style, feature

#82 :sparkles: board title 불러오기 구현
  src/components/container/Container.tsx
  src/pages/main/Main.tsx
Labels: component, feature

#84 :sparkles: feat : 이모지 선택시 outline 보이도록 설정
  src/components/emojiModal/EmojiModal.tsx
  src/components/emojiModal/emojiModalStyle.ts
Labels: style, feature

#85 :sparkles: feat: 공유 링크 추가
  src/components/container/Container.tsx
  src/components/deleteModal/DeleteModal.tsx
  src/components/emojiModal/EmojiModal.tsx
  src/components/shareModal/Share.tsx
  src/components/titleInput/titleInputStyle.tsx
  src/elements/buttons/button.tsx
  src/elements/buttons/shareBtn.tsx
  src/pages/board/Board.tsx
Labels: feature

#86 :sparkles: feat : done페이지 완성
  src/app/app.tsx
  src/components/container/Container.tsx
  src/pages/board/Board.tsx
  src/pages/fixedBoard/FixedBoard.tsx
Labels: page

#90 :truck: etc : header 폴더명 변경
  src/pages/board/Board.tsx
  src/pages/fixedBoard/FixedBoard.tsx
  src/pages/main/Main.tsx
Labels: etc

#91 :truck: etc : header 폴더명 변경
  src/components/header/Header.tsx
  src/components/header/headerStyle.tsx
Labels: etc

#92 :sparkles: feat: 카카오 공유 기능
  src/components/shareModal/Share.tsx
  src/components/shareModal/kakao.tsx
  src/elements/buttons/shareBtn.tsx
  src/pages/board/Board.tsx
Labels: feature

#93 :sparkles: feat: 클립보드에 복사하기 기능 추가
  src/components/shareModal/Share.tsx
Labels: feature

#94 :sparkles: feat: 클립보드 복사기능 추가
  src/components/shareModal/Share.tsx
Labels: feature

#95 :sparkles: feat: 카카오 공유기능 추가
  src/components/shareModal/Share.tsx
  src/components/shareModal/kakao.tsx
  src/elements/buttons/shareBtn.tsx
Labels: feature

#101 :lipstick: style : 전체적인 UI 수정
  src/components/emojiModal/emojiModalStyle.ts
  src/components/header/headerStyle.tsx
  src/components/shareModal/Share.tsx
  src/pages/board/Board.tsx
Labels: style

#104 :truck: modify : elements폴더 파일명, 경로 정리
  src/components/container/style.ts
  src/components/deleteModal/DeleteModal.tsx
  src/components/emojiModal/EmojiModal.tsx
  src/components/emojiModal/style.ts
  src/components/post/Post.tsx
  src/components/shareModal/Share.tsx
  src/components/titleInput/titleInputStyle.tsx
  src/elements/button/Button.tsx
  src/elements/button/style.ts
  src/elements/buttons/shareBtn.tsx
  src/elements/emoji/Emoji.tsx
  src/elements/image/Image.tsx
  src/elements/image/style.ts
  src/elements/input/Input.tsx
  src/elements/input/style.ts
  src/elements/textarea/Textarea.tsx
  src/elements/textarea/style.ts
  src/pages/board/Board.tsx
Labels: etc, refectoring

#106 :lipstick: fix : 로고 Link 태그 변경
  src/components/header/Header.tsx
Labels: refectoring

#105 :truck: modify: pages 스타일드컴포넌트 파일 분기, 경로 변경
  src/pages/board/Board.tsx
  src/pages/board/style.ts
  src/pages/fixedBoard/FixedBoard.tsx
  src/pages/main/Main.tsx
  src/pages/main/style.ts
Labels: refectoring

#112 modify : 중복되는 이미지 버튼 리팩토링 및 관련 컴포넌트 수정
  src/components/emojiModal/EmojiModal.tsx
  src/components/post/Post.tsx
  src/components/post/style.ts
  src/components/shareModal/Share.tsx
  src/elements/button/Button.tsx
  src/elements/button/style.ts
Labels: component, style, refectoring

#114 :art: modify : 공유모달창 리팩토링
  src/components/shareModal/Share.tsx
  src/components/shareModal/style.ts
  src/elements/button/Button.tsx
  src/elements/button/style.ts
Labels: component, style, feature, refectoring

#116 :art: modify : 링크 공유 버튼 리팩토링
  src/components/shareModal/Share.tsx
  src/elements/button/Button.tsx
  src/elements/button/style.ts
  src/pages/board/Board.tsx
Labels: feature, refectoring

#118 👔 update : 메인페이지 변경
  src/apis/posts.ts
  src/components/titleInput/TitleInput.tsx
  src/pages/main/Main.tsx
  src/typings/index.d.ts
Labels: page, feature

#120 🚚 modify : 랜덤컬러 함수 파일 분기
  src/components/container/Container.tsx
  src/components/container/colorPicker.ts
  src/components/deleteModal/DeleteModal.tsx
  src/components/post/Post.tsx
  src/components/post/style.ts
  src/elements/button/style.ts
Labels: style, refectoring

#121 :lipstick: add : 공유 모달창 미디어 쿼리 추가
  src/components/shareModal/Share.tsx
  src/components/shareModal/style.ts
  src/elements/button/Button.tsx
  src/elements/button/style.ts
Labels: component, style

#123 style : 생성된 board에서 타이틀 수정 button/input UI 구현
  src/components/container/Container.tsx
  src/components/container/style.ts
Labels: style
